=== antebm/FER-Open-Computing/gramatika.dtd
<!ELEMENT podaci (grad)*>
<!ATTLIST grad handle CDATA #REQUIRED>
<!ELEMENT grad (ime, drzava, regija, kultura, osnovan, znamenitosti, koordinate)>

<!ELEMENT ime (#PCDATA)>
<!ATTLIST ime unesco (DA | NE) #REQUIRED>

<!ELEMENT drzava (#PCDATA)>
<!ELEMENT regija (#PCDATA)>
<!ELEMENT kultura (#PCDATA)>
<!ELEMENT osnovan (#PCDATA)>
<!ELEMENT znamenitosti (znamenitost)*>
<!ATTLIST osnovan era (pr.Kr. | N.E.) #REQUIRED>
<!ELEMENT koordinate (#PCDATA)>

<!ELEMENT znamenitost (imeZnamenitosti)>
<!ELEMENT imeZnamenitosti (#PCDATA)>
<!ATTLIST imeZnamenitosti tipZnamenitosti (portal | zidine | luka | gradjevina) #REQUIRED>

=== antebm/FER-Open-Computing/podaci.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE podaci SYSTEM "gramatika.dtd">
<?xml-stylesheet type="text/xsl" href="pretvorba.xsl"?>

<podaci>
    <grad handle="Mycenae">
        <ime unesco="DA">Mikena</ime>
        <drzava>Grčka</drzava>
        <regija>Peloponez</regija>
        <kultura>Egejska</kultura>
        <osnovan era="pr.Kr.">2000</osnovan>
        <znamenitosti>
        <znamenitost>
            <imeZnamenitosti tipZnamenitosti="portal">Lavlja vrata</imeZnamenitosti>
        </znamenitost>
        <znamenitost>
            <imeZnamenitosti tipZnamenitosti="gradjevina">Atrejeva riznica</imeZnamenitosti>
        </znamenitost>
        <znamenitost>
            <imeZnamenitosti tipZnamenitosti="zidine">Kiklopske zidine</imeZnamenitosti>
        </znamenitost>
        </znamenitosti>
        <koordinate>37.72919415,22.754428825393703</koordinate>
    </grad>

    <grad handle="Carthage">
        <ime unesco="DA">Kartaga</ime>
        <drzava>Tunis</drzava>
        <regija>Tunis</regija>
        <kultura>Fenička</kultura>
        <osnovan era="pr.Kr.">814</osnovan>
        <znamenitosti>
         <znamenitost>
            <imeZnamenitosti tipZnamenitosti="gradjevina">Rimski amfiteatar</imeZnamenitosti>
            </znamenitost>
            <znamenitost>
             <imeZnamenitosti tipZnamenitosti="luka">Vojna Luka Koton Kartage</imeZnamenitosti>
            </znamenitost>
        </znamenitosti>
        <koordinate>36.851627,10.330441</koordinate>
    </grad>

    <grad handle="Babylon">
        <ime unesco="DA">Babilon</ime>
        <drzava>Irak</drzava>
        <regija>Mezopotamija</regija>
        <kultura>Akadska</kultura>
        <osnovan era="pr.Kr.">2400</osnovan>
        <znamenitosti>
            <znamenitost>
            <imeZnamenitosti tipZnamenitosti="portal">Ištarina vrata</imeZnamenitosti>
            </znamenitost>
        </znamenitosti>
        <koordinate>32.54211285,44.42127383323714</koordinate>
    </grad>

    <grad handle="Uruk">
        <ime unesco="DA">Uruk</ime>
        <drzava>Irak</drzava>
        <regija>Mezopotamija</regija>
        <kultura>Sumerska</kultura>
        <osnovan era="pr.Kr.">4000</osnovan>
        <znamenitosti>
            <znamenitost>
             <imeZnamenitosti tipZnamenitosti="gradjevina">Hram božice Inanna</imeZnamenitosti>
            </znamenitost>
        </znamenitosti>
        <koordinate>31.3216128,45.638327</koordinate>
    </grad>

    <grad handle="Memphis,_Egypt">
        <ime unesco="DA">Memfis</ime>
        <drzava>Egipat</drzava>
        <regija>Donji Egipat</regija>
        <kultura>Egipatska</kultura>
        <osnovan era="pr.Kr.">3500</osnovan>
        <znamenitosti>
            <znamenitost>
                <imeZnamenitosti tipZnamenitosti="gradjevina">Hram božice Hator</imeZnamenitosti>
            </znamenitost>
        </znamenitosti>
        <koordinate>29.8544582,31.25928716961478</koordinate>
    </grad>
</podaci>
